#
# _config.yml
# reflog
#
# Jekyll configuration - https://jekyllrb.com/docs/configuration/
#

exclude: [bin/*, Brewfile*, Gemfile*, justfile, README.md, LICENSE.md]
keep_files: [.git, .nojekyll, .well-known/apple-app-site-association.json]

# Site settings
url: https://phatbl.at # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
title: phatblat's reflog
description: >- # this means to ignore newlines until "baseurl:"
  a few SHAs from a journey through code
email: #ben@octop.ad
author: Ben Chatelain
simple_search: https://google.com/search
twitter_username: phatblat
github_username:  phatblat

# Serving
host: localhost
port: 4000
open_url: http://localhost:4000

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Build settings
markdown:    kramdown
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"
incremental: false

liquid:
  error_mode: strict

# Markdown Processors
# https://jekyllrb.com/docs/configuration/markdown/
# https://kramdown.gettalong.org/options.html
kramdown:
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  coderay_line_numbers: nil
  syntax_highlighter: coderay

# Plugin settings
jekyll-mentions:
  base_url: https://twitter.com
