# Site settings
url: "http://phatblat.com" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
title: "phatblat's reflog"
description: > # this means to ignore newlines until "baseurl:"
  a few SHAs from a journey through code
email: #ben@octop.ad
author: Ben Chatelain
simple_search: http://google.com/search
twitter_username: phatblat
github_username:  phatblat

# Serving
host: 0.0.0.0
port: 4000

# Default extension for new posts and pages
post_ext: markdown
page_ext: html

# Default templates for posts and pages
# Found in _templates/
post_layout: post
page_layout: page

# Format titles with titlecase?
titlecase: true

# Change default template file (in _templates/)
post_template: post
page_template: page
draft_template: draft

# Build settings
markdown: kramdown
kramdown:
  use_coderay: true
  coderay:
    coderay_line_numbers: list
    coderay_css: class

gems:
  - octopress-image-tag
  - octopress-codeblock
  - octopress-codefence
  - octopress-gist
  - octopress-solarized
